codecov:
  require_ci_to_pass: yes

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false  # if true: only post the comment if coverage changes
  require_base: no        # [yes :: must have a base report to post]
  require_head: yes       # [yes :: must have a head report to post]

coverage:
  status:
    project:
      default:
        target: auto
        # Allows a 5% drop from the previous base commit coverage,
        # because there are some flaky tests.
        threshold: 3%
