name: Check & Build

on:
  push:
    branches:
      - master
      - 'release-[0-9].[0-9]*'
  pull_request:
    branches:
      - master
      - 'release-[0-9].[0-9]*'

jobs:

  make:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Setup Go environment
      uses: actions/setup-go@v2
      with:
        go-version: '^1.15.0'

    - name: Cache Lint Tools
      id: cache-lint-tools
      uses: actions/cache@v2
      with:
        path: tools/bin
        key: ${{ runner.os }}-br-lint-tools-${{ hashFiles('tools/go.sum') }}

    - name: Make
      run: make
